In [5]:
import numpy as np

def factorizacion_LU(A):
    n = len(A)
    L = np.zeros_like(A, dtype=float)
    U = np.zeros_like(A, dtype=float)

    for j in range(n):
        L[j][j] = 1
        for i in range(j + 1):
            suma1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = A[i][j] - suma1
        for i in range(j, n):
            suma2 = sum(U[k][j] * L[i][k] for k in range(j))
            if U[j][j] == 0:
                raise ValueError("La matriz contiene un cero en la diagonal, no se puede realizar la factorización LU sin pivoteo.")
            L[i][j] = (A[i][j] - suma2) / U[j][j]

    return L, U

def resolver_Ly_b(L, b):
    y = np.zeros_like(b)
    for i in range(len(b)):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

def resolver_Ux_y(U, y):
    x = np.zeros_like(y)
    for i in range(len(y) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

def matriz_inversa(A):
    n = len(A)
    A_inv = np.zeros_like(A, dtype=float)
    L, U = factorizacion_LU(A)
    
    for i in range(n):
        e = np.zeros(n)
        e[i] = 1
        y = resolver_Ly_b(L, e)
        A_inv[:,i] = resolver_Ux_y(U, y)

    return A_inv

# Definir una matriz de prueba
A = np.array([[1, -2, 3, 2],
              [2, 5, -1, -3],
              [2, -3, 0, 1],
              [-1, 0, 3, 1]])

# Ejecutar la factorización LU
L, U = factorizacion_LU(A)

# Imprimir las matrices L y U
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Calcular la matriz inversa
A_inv = matriz_inversa(A)

# Imprimir la matriz inversa
print("\nMatriz Inversa A^-1:")
print(A_inv)


Matriz L:
[[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [ 2.          0.11111111  1.          0.        ]
 [-1.         -0.22222222 -0.85106383  1.        ]]

Matriz U:
[[ 1.         -2.          3.          2.        ]
 [ 0.          9.         -7.         -7.        ]
 [ 0.          0.         -5.22222222 -2.22222222]
 [ 0.          0.          0.         -0.44680851]]

Matriz Inversa A^-1:
[[ 4.28571429e-01  1.42857143e-01 -4.76190476e-02 -3.80952381e-01]
 [ 1.00000000e+00 -4.93432455e-17 -1.00000000e+00 -1.00000000e+00]
 [-5.71428571e-01  1.42857143e-01  6.19047619e-01  9.52380952e-01]
 [ 2.14285714e+00 -2.85714286e-01 -1.90476190e+00 -2.23809524e+00]]
